<?php

/**
 * @file
 * Contains functions and hooks for living_spaces_menus.module.
 */

use Drupal\user\UserInterface;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function living_spaces_menus_user_update(UserInterface $user) {
  $field = 'joined_spaces';
  if ($user->hasField($field)) {
    if (!$user->get($field)->equals($user->original->get($field))) {
      \Drupal::service('plugin.manager.menu.link')->rebuild();
    }
  }
}

/**
 * Implements hook_collapsible_menu_alter().
 */
function living_spaces_menus_collapsible_menu_alter(&$build) {
  $spaces_menu_key = 'menu_link_content:436e7a5e-7eb0-4ba7-928c-b9064865f174';

  $connection = \Drupal::database();

  $result = $connection->query("SELECT groups_field_data.langcode AS groups_field_data_langcode, groups_field_data.id AS id, groups_field_data.label, user__field_favorite_spaces.entity_id
        FROM groups_field_data AS groups_field_data
        LEFT JOIN user__joined_spaces AS user__joined_spaces ON (user__joined_spaces.joined_spaces_target_id = groups_field_data.id)
        LEFT JOIN user__field_favorite_spaces AS user__field_favorite_spaces ON (user__field_favorite_spaces.field_favorite_spaces_target_id = groups_field_data.id AND user__field_favorite_spaces.entity_id = user__joined_spaces.entity_id)
        WHERE (groups_field_data.status = '1') AND user__joined_spaces.entity_id=:current_user
            AND ((groups_field_data.is_default IS NULL) OR (groups_field_data.is_default = '0'))
            AND (groups_field_data.type NOT IN ('mail_counseling', 'on_site_counseling', 'telephone_counseling'))
        ORDER BY entity_id DESC, label ASC
        LIMIT 8 OFFSET 0", [':current_user' => \Drupal::currentUser()->id()])->fetchAll();

  if ($result) {
    $total_link = end($build['#items'][$spaces_menu_key]['below']);

    $build['#items'][$spaces_menu_key]['below'] = [];

    foreach($result as $key => $item) {
      $build['#items'][$spaces_menu_key]['below']['living_spaces_menus.space:' . $item->id] = [
        'is_expanded' => FALSE,
        'is_collapsed' => FALSE,
        'in_active_trail' => FALSE,
        'attributes' => new Attribute(),
        'title' => $item->label,
        'url' => Url::fromRoute('entity.group.canonical', ['group' => $item->id]),
        'below' => [],
      ];
    }

    array_push($build['#items'][$spaces_menu_key]['below'], $total_link);
  }
}
