living_spaces_event.living_spaces_event_type.*:
  type: config_entity
  label: 'Space event type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    uuid:
      type: string
