dependencies:
  config:
    - group.relationship_type.living_space-0c08cffdd29a2babffd
    - group.relationship_type.living_space-4a6c34d88d045acfa6c
    - group.relationship_type.living_space-8d417d3bd0b09858597
    - group.relationship_type.living_space-c01b49fefadc540aec0
    - group.relationship_type.living_space-f18f6184f0f78722787
    - group.relationship_type.living_space-group_node-agenda
    - group.relationship_type.living_space-group_node-protocol
settings:
  handler_settings:
    target_bundles:
      living_space-0c08cffdd29a2babffd: living_space-0c08cffdd29a2babffd
      living_space-4a6c34d88d045acfa6c: living_space-4a6c34d88d045acfa6c
      living_space-8d417d3bd0b09858597: living_space-8d417d3bd0b09858597
      living_space-c01b49fefadc540aec0: living_space-c01b49fefadc540aec0
      living_space-f18f6184f0f78722787: living_space-f18f6184f0f78722787
      living_space-group_node-agenda: living_space-group_node-agenda
      living_space-group_node-protocol: living_space-group_node-protocol
