permissions:
  - 'view living_spaces_event:event entity'
  - 'view living_spaces_event:event relationship'
  - 'view living_spaces_event:general entity'
  - 'view living_spaces_event:general relationship'
  - 'view living_spaces_event:room_occupied entity'
  - 'view living_spaces_event:room_occupied relationship'
  - 'view living_spaces_event:supervision entity'
  - 'view living_spaces_event:supervision relationship'
  - 'view living_spaces_event:training entity'
  - 'view living_spaces_event:training relationship'
