permissions:
  - 'overview living space events'
  - 'view living_spaces_event:event content'
  - 'view living_spaces_event:event entity'
  - 'view living_spaces_event:general content'
  - 'view living_spaces_event:general entity'
  - 'view living_spaces_event:room_occupied content'
  - 'view living_spaces_event:room_occupied entity'
  - 'view living_spaces_event:supervision content'
  - 'view living_spaces_event:supervision entity'
  - 'view living_spaces_event:training content'
  - 'view living_spaces_event:training entity'
