email_invited_user_to_the_event:
  subject: 'You have been invited to the event [event:title].'
  body: "You have been invited to the event [event:title]. Please click here [event:url] to RSVP.\r\n\r\n--  [site:name] team"
