display:
  default:
    display_options:
      footer:
        section_path:
          id: section_path
          table: views
          field: section_path
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: section_path
          label: ''
          empty: true
          bundle: events
          title: 'All events'
