<?php

/**
 * @file
 * Install, update and uninstall functions for the living_spaces install profile.
 */

/**
 * Implements hook_install().
 */
function living_spaces_install() {
  // First, do everything in standard profile.
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();
}

/**
 * Grant 'change own username' permission.
 */
function living_spaces_update_9001() {
  user_role_grant_permissions('authenticated', ['change own username']);
}
