dependencies:
  config:
    - group.relationship_type.department-group_membership
    - group.relationship_type.project_space-group_membership
settings:
  handler_settings:
    target_bundles:
      department-group_membership: department-group_membership
      project_space-group_membership: project_space-group_membership
