dependencies:
  config:
    - group.relationship_type.department-0c08cffdd29a2babffd95
    - group.relationship_type.department-3c116df195fcf5a1b49df
    - group.relationship_type.department-4a6c34d88d045acfa6c01
    - group.relationship_type.department-8d417d3bd0b09858597e9
    - group.relationship_type.department-c01b49fefadc540aec091
    - group.relationship_type.department-f18f6184f0f7872278793
    - group.relationship_type.department-group_node-agenda
    - group.relationship_type.department-group_node-protocol
    - group.relationship_type.project_space-0c08cffdd29a2babff
    - group.relationship_type.project_space-304c39b447cbf317ba
    - group.relationship_type.project_space-3c116df195fcf5a1b4
    - group.relationship_type.project_space-4a6c34d88d045acfa6
    - group.relationship_type.project_space-8d417d3bd0b0985859
    - group.relationship_type.project_space-c01b49fefadc540aec
    - group.relationship_type.project_space-f18f6184f0f7872278
    - group.relationship_type.project_space-group_node-agenda
settings:
  handler_settings:
    target_bundles:
      department-group_node-agenda: department-group_node-agenda
      department-3c116df195fcf5a1b49df: department-3c116df195fcf5a1b49df
      department-group_node-protocol: department-group_node-protocol
      department-4a6c34d88d045acfa6c01: department-4a6c34d88d045acfa6c01
      department-f18f6184f0f7872278793: department-f18f6184f0f7872278793
      department-8d417d3bd0b09858597e9: department-8d417d3bd0b09858597e9
      department-0c08cffdd29a2babffd95: department-0c08cffdd29a2babffd95
      department-c01b49fefadc540aec091: department-c01b49fefadc540aec091
      project_space-group_node-agenda: project_space-group_node-agenda
      project_space-3c116df195fcf5a1b4: project_space-3c116df195fcf5a1b4
      project_space-304c39b447cbf317ba: project_space-304c39b447cbf317ba
      project_space-4a6c34d88d045acfa6: project_space-4a6c34d88d045acfa6
      project_space-f18f6184f0f7872278: project_space-f18f6184f0f7872278
      project_space-8d417d3bd0b0985859: project_space-8d417d3bd0b0985859
      project_space-0c08cffdd29a2babff: project_space-0c08cffdd29a2babff
      project_space-c01b49fefadc540aec: project_space-c01b49fefadc540aec
