permissions:
  - 'create group_node:discussion_post entity'
  - 'create group_node:discussion_post relationship'
  - 'delete any group_node:discussion_post entity'
  - 'delete any group_node:discussion_post relationship'
  - 'delete own group_node:discussion_post entity'
  - 'delete own group_node:discussion_post relationship'
  - 'update any group_node:discussion_post entity'
  - 'update any group_node:discussion_post relationship'
  - 'update own group_node:discussion_post entity'
  - 'update own group_node:discussion_post relationship'
  - 'view group_node:discussion_post entity'
  - 'view group_node:discussion_post relationship'
  - 'view unpublished group_node:discussion_post entity'
