permissions:
  - 'create group_node:discussion_post entity'
  - 'delete any group_node:discussion_post entity'
  - 'update any group_node:discussion_post entity'
  - 'view group_node:discussion_post entity'
