display:
  member_of_circles:
    id: member_of_circles
    display_title: 'I am Member of Circles'
    display_plugin: page
    position: 1
    display_options:
      title: Spaces
      fields:
        label:
          id: label
          table: groups_field_data
          field: label
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: null
          entity_field: label
          plugin_id: field
          label: Title
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: true
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
        living_spaces_group_privacy_field:
          id: living_spaces_group_privacy_field
          table: groups_field_data
          field: living_spaces_group_privacy_field
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: group
          plugin_id: living_spaces_group_privacy_field
          label: Access
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
      access:
        type: perm
        options:
          perm: 'access living spaces overview'
      arguments:
        uid:
          id: uid
          table: users_field_data
          field: uid
          relationship: gc__user
          group_type: group
          admin_label: ''
          entity_type: user
          entity_field: uid
          plugin_id: user_uid
          default_action: default
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          default_argument_type: current_user
          default_argument_options: {  }
          default_argument_skip_url: false
          summary_options:
            base_path: ''
            count: true
            override: false
            items_per_page: 25
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: false
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: false
          not: false
      filters:
        type:
          id: type
          table: groups_field_data
          field: type
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: group
          entity_field: type
          plugin_id: bundle
          operator: in
          value:
            circle: circle
          group: 1
          exposed: false
          expose:
            operator_id: type_op
            label: Type
            description: ''
            use_operator: false
            operator: type_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: type
            required: false
            remember: false
            multiple: true
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              administrator: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
      filter_groups:
        operator: AND
        groups:
          1: AND
      defaults:
        access: false
        title: false
        group_by: false
        relationships: false
        fields: false
        arguments: false
        filters: false
        filter_groups: false
      relationships:
        group_content_id:
          id: group_content_id
          table: groups_field_data
          field: group_content_id
          relationship: none
          group_type: group
          admin_label: 'Group content'
          entity_type: group
          plugin_id: group_to_group_content
          required: false
          group_content_plugins:
            group_membership: group_membership
            'dip_chat_appointment:chat_appointment': '0'
            'dip_mail_shift:mail_shift': '0'
            'group_node:agenda': '0'
            'group_node:changelog': '0'
            'group_node:discussion_post': '0'
            'group_node:page': '0'
            'group_node:protocol': '0'
            'living_spaces_event:event': '0'
            'living_spaces_event:general': '0'
            'living_spaces_event:room_occupied': '0'
            'living_spaces_event:supervision': '0'
            'living_spaces_event:training': '0'
        gc__user:
          id: gc__user
          table: group_content_field_data
          field: gc__user
          relationship: group_content_id
          group_type: group
          admin_label: 'Group content User'
          entity_type: group_content
          plugin_id: group_content_to_entity
          required: false
          group_content_plugins:
            group_membership: group_membership
      group_by: false
      display_description: ''
      display_extenders: {  }
      path: membership/circles
      menu:
        type: tab
        title: 'I am Member of Circles'
        description: 'I am a member of Circles'
        weight: 0
        expanded: false
        menu_name: main
        parent: living_spaces_menus.membership_link
        context: '0'
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user
        - user.permissions
      tags: {  }
