definitions:
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -10
  user__logout:
    enabled: false
    menu_name: account
    parent: ''
    weight: 10
    expanded: false
