permissions:
  - 'delete own group_node:agenda entity'
  - 'update own group_node:agenda entity'
  - 'view group_node:agenda entity'
  - 'view private group'
  - 'view public group'
  - 'view published pages'
  - 'view discussions section of a living space'
  - 'view events section of a living space'
