permissions:
  - 'create living_spaces_event:event entity'
  - 'create living_spaces_event:general entity'
  - 'create living_spaces_event:room_occupied entity'
  - 'create living_spaces_event:supervision entity'
  - 'create living_spaces_event:training entity'
  - 'delete any living_spaces_event:event entity'
  - 'delete any living_spaces_event:general entity'
  - 'delete any living_spaces_event:room_occupied entity'
  - 'delete any living_spaces_event:supervision entity'
  - 'delete any living_spaces_event:training entity'
  - 'delete own living_spaces_event:event entity'
  - 'delete own living_spaces_event:general entity'
  - 'delete own living_spaces_event:general relationship'
  - 'delete own living_spaces_event:room_occupied entity'
  - 'delete own living_spaces_event:room_occupied relationship'
  - 'delete own living_spaces_event:supervision entity'
  - 'delete own living_spaces_event:supervision relationship'
  - 'delete own living_spaces_event:training entity'
  - 'delete own living_spaces_event:training relationship'
  - 'update any living_spaces_event:event entity'
  - 'update any living_spaces_event:general entity'
  - 'update any living_spaces_event:room_occupied entity'
  - 'update any living_spaces_event:supervision entity'
  - 'update any living_spaces_event:training entity'
  - 'update own living_spaces_event:event entity'
  - 'update own living_spaces_event:general entity'
  - 'update own living_spaces_event:general relationship'
  - 'update own living_spaces_event:room_occupied entity'
  - 'update own living_spaces_event:room_occupied relationship'
  - 'update own living_spaces_event:supervision entity'
  - 'update own living_spaces_event:supervision relationship'
  - 'update own living_spaces_event:training entity'
  - 'update own living_spaces_event:training relationship'
  - 'view living_spaces_event:event entity'
  - 'view living_spaces_event:event relationship'
  - 'view living_spaces_event:general entity'
  - 'view living_spaces_event:general relationship'
  - 'view living_spaces_event:room_occupied entity'
  - 'view living_spaces_event:room_occupied relationship'
  - 'view living_spaces_event:supervision entity'
  - 'view living_spaces_event:supervision relationship'
  - 'view living_spaces_event:training entity'
  - 'view living_spaces_event:training relationship'
  - 'view own unpublished living_spaces_event:event entity'
  - 'view own unpublished living_spaces_event:general entity'
  - 'view own unpublished living_spaces_event:room_occupied entity'
  - 'view own unpublished living_spaces_event:supervision entity'
  - 'view own unpublished living_spaces_event:training entity'
