permissions:
  - 'delete own group_node:agenda entity'
  - 'update own group_node:agenda entity'
  - 'view group_node:agenda entity'
  - 'view private group'
  - 'view public group'
  - 'view discussions section of a living space'
  - 'view events section of a living space'
  - 'delete own living_spaces_event:supervision entity'
  - 'delete own living_spaces_event:supervision relationship'
  - 'delete own living_spaces_event:training entity'
  - 'delete own living_spaces_event:training relationship'
  - 'update own living_spaces_event:room_occupied entity'
  - 'update own living_spaces_event:supervision relationship'
  - 'update own living_spaces_event:training relationship'
  - 'view living_spaces_event:event entity'
  - 'view living_spaces_event:event relationship'
  - 'view living_spaces_event:general entity'
  - 'view living_spaces_event:general relationship'
  - 'view living_spaces_event:room_occupied entity'
  - 'view living_spaces_event:room_occupied relationship'
  - 'view living_spaces_event:supervision entity'
  - 'view living_spaces_event:supervision relationship'
  - 'view living_spaces_event:training entity'
  - 'view living_spaces_event:training relationship'
  - 'view own unpublished living_spaces_event:general entity'
  - 'view own unpublished living_spaces_event:room_occupied entity'
  - 'view own unpublished living_spaces_event:supervision entity'
  - 'view own unpublished living_spaces_event:training entity'
