weight: -9
permissions:
  - 'access circles overview'
  - 'access content'
  - 'access living spaces overview'
  - 'access simple permissions'
  - 'access user profiles'
  - 'add members to any space'
  - 'administer permissions'
  - 'assign assistant_to_the_office_manager role'
  - 'assign client_admin role'
  - 'assign counselee role'
  - 'assign external_employee role'
  - 'assign former_employee role'
  - 'assign full_time_employee role'
  - 'assign office_manager role'
  - 'assign trainee_intern role'
  - 'assign trainer_mentor role'
  - 'assign volunteer role'
  - 'cancel account'
  - 'create agenda content'
  - 'create circle group'
  - 'create department group'
  - 'create discussion_post content'
  - 'create living_space group'
  - 'create paragraph content agenda_item'
  - 'create project_space group'
  - 'delete any agenda content'
  - 'delete any discussion_post content'
  - 'delete own discussion_post content'
  - 'delete paragraph content agenda_item'
  - 'delete shared offices space members'
  - 'edit any agenda content'
  - 'edit any discussion_post content'
  - 'edit own agenda content'
  - 'edit own discussion_post content'
  - 'living space create employees'
  - 'manage circle spaces'
  - 'manage employee profiles'
  - 'manage living spaces'
  - 'select account cancellation method'
  - 'update paragraph content agenda_item'
  - 'view own profile'
  - 'view own unpublished content'
  - 'view paragraph content agenda_item'
  - 'view paragraph content faq'
  - 'view user email addresses'
