permissions:
  - 'access content'
  - 'create agenda content'
  - 'create paragraph content agenda_item'
  - 'delete paragraph content agenda_item'
  - 'edit own agenda content'
  - 'update paragraph content agenda_item'
  - 'view own profile'
  - 'view own unpublished content'
  - 'view paragraph content agenda_item'
  - 'view paragraph content faq'
