permissions:
  - 'access comments'
  - 'access content'
  - 'access intranet dashboard'
  - 'access shortcuts'
  - 'access site-wide contact form'
  - 'change own username'
  - 'post comments'
  - 'search content'
  - 'skip comment approval'
  - 'use text format basic_html'
