permissions:
  - 'access circles overview'
  - 'access content'
  - 'access flood unblock'
  - 'access living spaces overview'
  - 'access simple permissions'
  - 'administer living spaces sections settings'
  - 'administer permissions'
  - 'create agenda content'
  - 'create department group'
  - 'create discussion_post content'
  - 'create paragraph content agenda_item'
  - 'delete any agenda content'
  - 'delete any discussion_post content'
  - 'delete own discussion_post content'
  - 'delete paragraph content agenda_item'
  - 'edit any agenda content'
  - 'edit any discussion_post content'
  - 'edit own agenda content'
  - 'edit own discussion_post content'
  - 'living space create employees'
  - 'manage circle spaces'
  - 'manage employee profiles'
  - 'update paragraph content agenda_item'
  - 'view own profile'
  - 'view own unpublished content'
  - 'view paragraph content agenda_item'
  - 'view paragraph content faq'
