permissions:
  - 'access circles overview'
  - 'access content'
  - 'access employees overview'
  - 'access living spaces overview'
  - 'access user profiles'
  - 'add members to administered space'
  - 'administer permissions'
  - 'assign assistant_to_the_office_manager role'
  - 'assign counselee role'
  - 'assign external_employee role'
  - 'assign former_employee role'
  - 'assign full_time_employee role'
  - 'assign office_manager role'
  - 'assign trainee_intern role'
  - 'assign trainer_mentor role'
  - 'assign volunteer role'
  - 'cancel account'
  - 'change member passwords'
  - 'create agenda content'
  - 'create circle group'
  - 'create contact_data profile'
  - 'create core profile'
  - 'create living_space group'
  - 'create paragraph content agenda_item'
  - 'delete own agenda content'
  - 'delete own contact_data profile'
  - 'delete own core profile'
  - 'delete paragraph content agenda_item'
  - 'delete shared offices space members'
  - 'edit own agenda content'
  - 'living space create employees'
  - 'overview messages'
  - 'select account cancellation method'
  - 'update own contact_data profile'
  - 'update own core profile'
  - 'update paragraph content agenda_item'
  - 'view own contact_data profile'
  - 'view own core profile'
  - 'view own profile'
  - 'view own unpublished content'
  - 'view paragraph content agenda_item'
  - 'view paragraph content faq'
  - 'view user email addresses'
