permissions:
  - 'access circles overview'
  - 'access employees overview'
  - 'access living spaces overview'
  - 'create contact_data profile'
  - 'create core profile'
  - 'delete own contact_data profile'
  - 'delete own core profile'
  - 'living space create employees'
  - 'update own contact_data profile'
  - 'update own core profile'
  - 'view own contact_data profile'
  - 'view own core profile'
  - 'view own profile'
