permissions:
  - 'access circles overview'
  - 'access content'
  - 'access employees overview'
  - 'access living spaces overview'
  - 'access user profiles'
  - 'cancel account'
  - 'create agenda content'
  - 'create paragraph content agenda_item'
  - 'delete own agenda content'
  - 'delete paragraph content agenda_item'
  - 'edit own agenda content'
  - 'living space create employees'
  - 'select account cancellation method'
  - 'update paragraph content agenda_item'
  - 'view own profile'
  - 'view own unpublished content'
  - 'view paragraph content agenda_item'
  - 'view paragraph content faq'
  - 'view user email addresses'
  - 'delete shared offices space members'
