display:
  default:
    display_options:
      filters:
        message:
          id: message
          table: watchdog
          field: message
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: string
          operator: word
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: message_op
            label: Search
            description: ''
            use_operator: false
            operator: message_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: message
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              administrator: '0'
              client_admin: '0'
              office_manager: '0'
              full_time_employee: '0'
              former_employee: '0'
              counselee: '0'
              anonymous: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
        uid:
          id: uid
          table: users_field_data
          field: uid
          relationship: uid
          group_type: group
          admin_label: ''
          entity_type: user
          entity_field: uid
          plugin_id: user_name
          operator: in
          value: {  }
          group: 1
          exposed: true
          expose:
            operator_id: uid_op
            label: Name
            description: ''
            use_operator: false
            operator: uid_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: uid
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              administrator: '0'
              client_admin: '0'
              office_manager: '0'
              full_time_employee: '0'
              former_employee: '0'
              counselee: '0'
              anonymous: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
