dependencies:
  config:
    - field.storage.taxonomy_term.field_custom_id
display:
  rest:
    display_options:
      fields:
        field_custom_id:
          id: field_custom_id
          table: taxonomy_term__field_custom_id
          field: field_custom_id
          relationship: field_category
          group_type: group
          admin_label: ''
          plugin_id: field
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: false
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
      pager:
        type: none
        options:
          offset: 0
      access:
        type: none
        options: {  }
      filters:
        field_availability_value:
          id: field_availability_value
          table: taxonomy_term__field_availability
          field: field_availability_value
          relationship: field_category
          group_type: group
          admin_label: ''
          plugin_id: list_field
          operator: or
          value:
            w: w
          group: 1
          exposed: false
          expose:
            operator_id: ''
            label: ''
            description: ''
            use_operator: false
            operator: ''
            operator_limit_selection: false
            operator_list: {  }
            identifier: ''
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          reduce_duplicates: false
        field_custom_id_value:
          id: field_custom_id_value
          table: taxonomy_term__field_custom_id
          field: field_custom_id_value
          relationship: field_category
          group_type: group
          admin_label: ''
          plugin_id: string
          operator: '='
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: field_custom_id_value_op
            label: 'Custom ID'
            description: ''
            use_operator: false
            operator: field_custom_id_value_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: categoryID
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              administrator: '0'
              client_admin: '0'
              office_manager: '0'
              full_time_employee: '0'
              former_employee: '0'
              counselee: '0'
              anonymous: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
      row:
        options:
          field_options:
            field_custom_id:
              alias: categoryID
              raw_output: false
      defaults:
        access: false
        relationships: false
        fields: false
        filters: false
        filter_groups: false
      relationships:
        field_category:
          id: field_category
          table: paragraph__field_category
          field: field_category
          relationship: none
          group_type: group
          admin_label: Category
          plugin_id: standard
          required: false
      path: api/v1.0/faq
    cache_metadata:
      tags:
        - 'config:field.storage.taxonomy_term.field_custom_id'
