dependencies:
  module:
    - group
field_settings:
  joined_spaces:
    label: Spaces
    datasource_id: 'entity:user'
    property_path: joined_spaces
    type: solr_text_unstemmed
    dependencies: {  }
  joined_spaces_ids:
    label: Spaces
    datasource_id: 'entity:user'
    property_path: joined_spaces
    type: integer
    dependencies: {  }
  label:
    label: 'Spaces » Group » Title'
    datasource_id: 'entity:user'
    property_path: 'joined_spaces:entity:label'
    type: solr_text_unstemmed
    dependencies:
      module:
        - group
  ngram_label:
    label: 'Spaces » Group » Title'
    datasource_id: 'entity:user'
    property_path: 'joined_spaces:entity:label'
    type: 'solr_text_custom:ngram'
    dependencies:
      module:
        - group
