email_new_space_member:
  subject: 'You have been added to a new space'
  body: "Hello [user:display-name], we would like to inform you that you have been added to a new room.\r\n\r\nBest regards\r\nYour [site:name] team"
email_delete_space_member:
  subject: 'You were removed from the space'
  body: "Hello [user:display-name], We regret to inform you that you have been removed from a room.\r\n\r\nBest regards\r\nYour [site:name] team"
