display:
  employee:
    display_options:
      fields:
        joined_spaces:
          id: joined_spaces
          table: search_api_index_space_users
          field: joined_spaces
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api_field
          label: Spaces
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          field_rendering: true
          fallback_handler: search_api_entity
          fallback_options:
            link_to_item: false
            use_highlighting: false
            multi_type: separator
            multi_separator: ', '
            display_methods: {  }
      arguments:
        joined_spaces_ids:
          id: joined_spaces_ids
          table: search_api_index_space_users
          field: joined_spaces_ids
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api
          default_action: default
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          default_argument_type: living_spaces_group_joined_spaces
          default_argument_options: {  }
          default_argument_skip_url: false
          summary_options: {  }
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: true
          validate:
            type: 'entity:group'
            fail: empty
          validate_options:
            bundles: {  }
            access: false
            operation: view
            multiple: 1
          break_phrase: true
          not: false
      style:
        options:
          columns:
            joined_spaces: joined_spaces
          info:
            joined_spaces:
              sortable: false
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: false
              responsive: ''
  employee_export:
    display_options:
      fields:
        joined_spaces:
          id: joined_spaces
          table: search_api_index_space_users
          field: joined_spaces
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api_field
          label: Spaces
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          field_rendering: true
          fallback_handler: search_api_entity
          fallback_options:
            link_to_item: false
            use_highlighting: false
            multi_type: separator
            multi_separator: ', '
            display_methods:
              circle:
                display_method: label
              department:
                display_method: label
                view_mode: default
              living_space:
                display_method: label
                view_mode: default
              project_space:
                display_method: label
                view_mode: default
      arguments:
        joined_spaces_ids:
          id: joined_spaces_ids
          table: search_api_index_space_users
          field: joined_spaces_ids
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api
          default_action: default
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          default_argument_type: living_spaces_group_joined_spaces
          default_argument_options: {  }
          default_argument_skip_url: false
          summary_options: {  }
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: true
          validate:
            type: 'entity:group'
            fail: empty
          validate_options:
            bundles: {  }
            access: false
            operation: view
            multiple: 1
          break_phrase: true
          not: false
      row:
        options:
          field_options:
            joined_spaces:
              alias: ''
              raw_output: false
